-- SmartProZen Preloaded Pages
-- Complete set of preloaded pages with customizable sections

-- Insert preloaded pages
INSERT INTO `pages` (`title`, `slug`, `content`, `template_slug`, `meta_title`, `meta_description`, `is_published`, `is_homepage`) VALUES
('Home', 'home', '{}', 'default_page', 'SmartProZen - Smart Tech, Simplified Living', 'Discover our curated collection of smart gadgets and professional accessories designed to elevate your everyday.', 1, 1),
('About Us', 'about', '{}', 'default_page', 'About Us - SmartProZen', 'Learn about SmartProZen and our mission to provide smart technology solutions for modern living.', 1, 0),
('Contact', 'contact', '{}', 'default_page', 'Contact Us - SmartProZen', 'Get in touch with SmartProZen for support, questions, or business inquiries.', 1, 0),
('Products', 'products', '{}', 'default_page', 'Products - SmartProZen', 'Browse our complete collection of smart gadgets and professional accessories.', 1, 0),
('Blog', 'blog', '{}', 'default_page', 'Blog - SmartProZen', 'Stay updated with the latest tech news, reviews, and insights from SmartProZen.', 1, 0),
('Shipping Information', 'shipping', '{}', 'default_page', 'Shipping Information - SmartProZen', 'Learn about our shipping options, delivery times, and shipping policies.', 1, 0),
('Returns & Exchanges', 'returns', '{}', 'default_page', 'Returns & Exchanges - SmartProZen', 'Our hassle-free returns and exchange policy for your peace of mind.', 1, 0),
('Privacy Policy', 'privacy', '{}', 'default_page', 'Privacy Policy - SmartProZen', 'How we collect, use, and protect your personal information.', 1, 0),
('Terms of Service', 'terms', '{}', 'default_page', 'Terms of Service - SmartProZen', 'Terms and conditions for using SmartProZen services.', 1, 0);

-- Insert homepage sections
INSERT INTO `page_sections` (`page_id`, `section_type`, `content_json`, `display_order`, `is_published`) VALUES
(1, 'hero', '{"title_en": "Smart Tech, Simplified Living", "subtitle_en": "Discover our curated collection of smart gadgets and professional accessories designed to elevate your everyday.", "button_text_en": "Shop Now", "button_url": "/products", "background_image": "/uploads/sections/hero-bg.jpg", "title_bn": "স্মার্ট টেক, সরল জীবন", "subtitle_bn": "আপনার দৈনন্দিন জীবনকে উন্নত করার জন্য ডিজাইন করা স্মার্ট গ্যাজেট এবং পেশাদার আনুষাঙ্গিকগুলির আমাদের কিউরেটেড সংগ্রহ আবিষ্কার করুন।", "button_text_bn": "এখনই কিনুন"}', 1, 1),
(1, 'featured_products', '{"title_en": "Our Most Popular Products", "subtitle_en": "Handpicked favorites from our collection", "products_limit": 6, "show_ratings": true, "title_bn": "আমাদের সবচেয়ে জনপ্রিয় পণ্য", "subtitle_bn": "আমাদের সংগ্রহ থেকে হ্যান্ডপিক করা প্রিয়"}', 2, 1),
(1, 'features', '{"title_en": "The SmartProZen Advantage", "subtitle_en": "Why choose us for your smart tech needs", "features": [{"icon": "bi-gem", "title_en": "Premium Quality", "description_en": "We source and test every product to ensure it meets our high standards."}, {"icon": "bi-truck", "title_en": "Fast & Free Shipping", "description_en": "Get your order delivered quickly. Free shipping on orders over $50."}, {"icon": "bi-shield-check", "title_en": "Secure Checkout", "description_en": "Your privacy and security are our top priority."}, {"icon": "bi-headset", "title_en": "24/7 Support", "description_en": "Our dedicated support team is here to help you around the clock."}], "title_bn": "স্মার্টপ্রোজেন সুবিধা", "subtitle_bn": "আপনার স্মার্ট টেকের প্রয়োজনে কেন আমাদের বেছে নিন"}', 3, 1),
(1, 'testimonials', '{"title_en": "Loved by Professionals Like You", "subtitle_en": "See what our customers have to say", "testimonials_limit": 4, "show_avatars": true, "title_bn": "আপনার মতো পেশাদারদের দ্বারা পছন্দ", "subtitle_bn": "আমাদের গ্রাহকদের কী বলতে হয় তা দেখুন"}', 4, 1),
(1, 'pricing', '{"title_en": "Choose Your Plan", "subtitle_en": "Flexible options for every need", "show_currency": true, "currency": "USD", "title_bn": "আপনার প্ল্যান বেছে নিন", "subtitle_bn": "প্রতিটি প্রয়োজনের জন্য নমনীয় বিকল্প"}', 5, 1),
(1, 'faq', '{"title_en": "Frequently Asked Questions", "subtitle_en": "Get answers to common questions", "faqs": [{"question_en": "What is your return policy?", "answer_en": "We offer a 30-day return policy for all products in original condition."}, {"question_en": "Do you ship internationally?", "answer_en": "Yes, we ship to most countries worldwide. Shipping costs vary by location."}, {"question_en": "How long does shipping take?", "answer_en": "Standard shipping takes 3-5 business days. Express shipping is available."}, {"question_en": "Are your products covered by warranty?", "answer_en": "All products come with manufacturer warranty. Extended warranties are available."}], "title_bn": "প্রায়শই জিজ্ঞাসিত প্রশ্ন", "subtitle_bn": "সাধারণ প্রশ্নের উত্তর পান"}', 6, 1);

-- Insert about page sections
INSERT INTO `page_sections` (`page_id`, `section_type`, `content_json`, `display_order`, `is_published`) VALUES
(2, 'hero', '{"title_en": "About SmartProZen", "subtitle_en": "Empowering modern living through smart technology", "background_image": "/uploads/sections/about-hero.jpg", "title_bn": "স্মার্টপ্রোজেন সম্পর্কে", "subtitle_bn": "স্মার্ট প্রযুক্তির মাধ্যমে আধুনিক জীবনকে ক্ষমতায়ন"}', 1, 1),
(2, 'rich_text', '{"content_en": "<h3>Our Story</h3><p>Founded in 2020, SmartProZen emerged from a simple belief: technology should enhance our lives, not complicate them. We started as a small team of tech enthusiasts who were frustrated with the overwhelming complexity of smart devices.</p><p>Today, we are proud to offer a curated selection of smart gadgets and professional accessories that truly make a difference. Every product in our collection is carefully tested and selected based on quality, functionality, and user experience.</p><h3>Our Mission</h3><p>To simplify technology adoption by providing high-quality, user-friendly smart devices that seamlessly integrate into modern lifestyles.</p><h3>Our Values</h3><ul><li><strong>Quality First:</strong> We never compromise on quality</li><li><strong>User-Centric:</strong> Every decision is made with our customers in mind</li><li><strong>Innovation:</strong> We embrace new technologies that add real value</li><li><strong>Integrity:</strong> Honest business practices and transparent communication</li></ul>", "content_bn": "<h3>আমাদের গল্প</h3><p>২০২০ সালে প্রতিষ্ঠিত, স্মার্টপ্রোজেন একটি সাধারণ বিশ্বাস থেকে উদ্ভূত হয়েছে: প্রযুক্তি আমাদের জীবনকে উন্নত করবে, জটিল করবে না।</p>"}', 2, 1),
(2, 'testimonials', '{"title_en": "What Our Customers Say", "subtitle_en": "Real feedback from real customers", "testimonials_limit": 3, "title_bn": "আমাদের গ্রাহকরা কী বলেন", "subtitle_bn": "আসল গ্রাহকদের কাছ থেকে আসল প্রতিক্রিয়া"}', 3, 1);

-- Insert contact page sections
INSERT INTO `page_sections` (`page_id`, `section_type`, `content_json`, `display_order`, `is_published`) VALUES
(3, 'hero', '{"title_en": "Contact Us", "subtitle_en": "We would love to hear from you", "title_bn": "যোগাযোগ করুন", "subtitle_bn": "আমরা আপনার কাছ থেকে শুনতে পছন্দ করব"}', 1, 1),
(3, 'rich_text', '{"content_en": "<div class=\"row\"><div class=\"col-md-6\"><h4>Get in Touch</h4><p>Have a question or need help? We are here to assist you. Reach out to us through any of the channels below.</p><div class=\"contact-info\"><p><strong>Email:</strong> info@smartprozen.com</p><p><strong>Phone:</strong> +1 (555) 123-4567</p><p><strong>Address:</strong> 123 Tech Street, Innovation City, IC 12345</p></div></div><div class=\"col-md-6\"><h4>Business Hours</h4><p><strong>Monday - Friday:</strong> 9:00 AM - 6:00 PM</p><p><strong>Saturday:</strong> 10:00 AM - 4:00 PM</p><p><strong>Sunday:</strong> Closed</p></div></div>", "content_bn": "<div class=\"row\"><div class=\"col-md-6\"><h4>যোগাযোগ করুন</h4><p>কোন প্রশ্ন আছে বা সাহায্য দরকার? আমরা আপনাকে সহায়তা করতে এখানে আছি।</p></div></div>"}', 2, 1);

-- Insert section templates
INSERT INTO `section_templates` (`name`, `section_type`, `content_json`, `preview_image`, `category`, `is_active`) VALUES
('Hero with Video Background', 'hero', '{"title_en": "Your Amazing Title", "subtitle_en": "Compelling subtitle that engages visitors", "button_text_en": "Call to Action", "button_url": "#", "video_url": "https://example.com/video.mp4", "background_overlay": true, "title_bn": "আপনার আশ্চর্যজনক শিরোনাম", "subtitle_bn": "মূলবান উপশিরোনাম যা দর্শকদের আকর্ষণ করে", "button_text_bn": "কল টু অ্যাকশন"}', '/uploads/templates/hero-video.jpg', 'hero', 1),
('Product Showcase Grid', 'featured_products', '{"title_en": "Featured Products", "subtitle_en": "Discover our best-selling items", "products_limit": 4, "show_ratings": true, "show_prices": true, "grid_columns": 4, "title_bn": "বৈশিষ্ট্যযুক্ত পণ্য", "subtitle_bn": "আমাদের সেরা বিক্রিত আইটেম আবিষ্কার করুন"}', '/uploads/templates/product-grid.jpg', 'products', 1),
('Features with Icons', 'features', '{"title_en": "Why Choose Us", "subtitle_en": "Here are some compelling reasons", "features": [{"icon": "bi-star", "title_en": "Premium Quality", "description_en": "High-quality products that last"}, {"icon": "bi-lightning", "title_en": "Fast Delivery", "description_en": "Quick and reliable shipping"}, {"icon": "bi-shield", "title_en": "Secure", "description_en": "Safe and secure transactions"}], "layout": "grid", "title_bn": "কেন আমাদের বেছে নিন", "subtitle_bn": "এখানে কিছু আকর্ষক কারণ রয়েছে"}', '/uploads/templates/features-icons.jpg', 'features', 1),
('Testimonials Carousel', 'testimonials', '{"title_en": "Customer Reviews", "subtitle_en": "What our customers are saying", "testimonials_limit": 6, "show_avatars": true, "show_ratings": true, "layout": "carousel", "autoplay": true, "title_bn": "গ্রাহক পর্যালোচনা", "subtitle_bn": "আমাদের গ্রাহকরা কী বলছেন"}', '/uploads/templates/testimonials-carousel.jpg', 'testimonials', 1),
('FAQ Accordion', 'faq', '{"title_en": "Frequently Asked Questions", "subtitle_en": "Find answers to common questions", "faqs": [{"question_en": "How can I track my order?", "answer_en": "You can track your order using the tracking number sent to your email."}, {"question_en": "What is your return policy?", "answer_en": "We offer a 30-day return policy for all products."}], "layout": "accordion", "title_bn": "প্রায়শই জিজ্ঞাসিত প্রশ্ন", "subtitle_bn": "সাধারণ প্রশ্নের উত্তর খুঁজুন"}', '/uploads/templates/faq-accordion.jpg', 'faq', 1),
('Rich Text Block', 'rich_text', '{"content_en": "<h2>Your Content Here</h2><p>Add your custom content with full HTML support. You can include headings, paragraphs, lists, images, and more.</p><ul><li>Feature 1</li><li>Feature 2</li><li>Feature 3</li></ul>", "content_bn": "<h2>এখানে আপনার বিষয়বস্তু</h2><p>সম্পূর্ণ HTML সমর্থন সহ আপনার কাস্টম বিষয়বস্তু যোগ করুন।</p>"}', '/uploads/templates/rich-text.jpg', 'content', 1);
