-- SmartProZen Sample Data - Part 3
-- Products and sample data

-- Insert sample products
INSERT INTO `products` (`name`, `slug`, `description`, `short_description`, `sku`, `price`, `sale_price`, `stock_quantity`, `stock_status`, `weight`, `product_type`, `featured_image`, `category_id`, `meta_title`, `meta_description`, `is_featured`, `is_published`) VALUES
('ZenBuds Pro 3', 'zenbuds-pro-3', 'Experience wireless audio like never before with ZenBuds Pro 3. Featuring advanced noise cancellation, 30-hour battery life, and crystal-clear sound quality. Perfect for professionals who demand the best audio experience.', 'Premium wireless earbuds with noise cancellation and 30-hour battery life.', 'ZBP3-001', 89.99, 79.99, 50, 'instock', 0.15, 'physical', '/uploads/products/zenbuds-pro-3.jpg', 2, 'ZenBuds Pro 3 - Premium Wireless Earbuds', 'Experience premium wireless audio with ZenBuds Pro 3 featuring noise cancellation and 30-hour battery life.', 1, 1),
('SmartGlow Ambient Light', 'smartglow-ambient-light', 'Create the perfect atmosphere with SmartGlow Ambient Light. Features 16 million colors, music sync, voice control, and smart scheduling. Compatible with Alexa and Google Assistant.', 'Smart LED light with 16M colors, music sync, and voice control.', 'SGL-001', 59.99, 49.99, 75, 'instock', 0.8, 'physical', '/uploads/products/smartglow-ambient-light.jpg', 1, 'SmartGlow Ambient Light - Smart LED Light', 'Create perfect ambiance with SmartGlow featuring 16M colors, music sync, and voice control.', 1, 1),
('ProCharge Wireless Stand', 'procharge-wireless-stand', 'Charge your devices efficiently with ProCharge Wireless Stand. Supports fast charging, multiple device compatibility, and features a sleek aluminum design. Perfect for your desk or nightstand.', 'Fast wireless charging stand with sleek aluminum design.', 'PCS-001', 45.00, 39.99, 100, 'instock', 0.5, 'physical', '/uploads/products/procharge-wireless-stand.jpg', 3, 'ProCharge Wireless Stand - Fast Charging', 'Efficiently charge your devices with ProCharge Wireless Stand featuring fast charging and sleek design.', 1, 1),
('ZenWatch Sport', 'zenwatch-sport', 'Track your fitness and stay connected with ZenWatch Sport. Features GPS, heart rate monitoring, 7-day battery life, and waterproof design. Perfect for athletes and fitness enthusiasts.', 'Smart fitness watch with GPS, heart rate monitoring, and 7-day battery life.', 'ZWS-001', 199.99, 179.99, 30, 'instock', 0.3, 'physical', '/uploads/products/zenwatch-sport.jpg', 4, 'ZenWatch Sport - Smart Fitness Watch', 'Track fitness and stay connected with ZenWatch Sport featuring GPS and heart rate monitoring.', 1, 1),
('GameMaster Pro Keyboard', 'gamemaster-pro-keyboard', 'Dominate the competition with GameMaster Pro Keyboard. Features mechanical switches, RGB lighting, programmable keys, and anti-ghosting technology. Built for professional gamers.', 'Mechanical gaming keyboard with RGB lighting and programmable keys.', 'GMP-KB-001', 129.99, 119.99, 40, 'instock', 1.2, 'physical', '/uploads/products/gamemaster-pro-keyboard.jpg', 5, 'GameMaster Pro Keyboard - Mechanical Gaming', 'Dominate with GameMaster Pro Keyboard featuring mechanical switches and RGB lighting.', 1, 1),
('Productivity Suite Pro', 'productivity-suite-pro', 'Boost your productivity with our comprehensive digital suite. Includes task management, time tracking, note-taking, and collaboration tools. Perfect for professionals and teams.', 'Comprehensive digital productivity suite with task management and collaboration tools.', 'PSP-001', 49.99, 39.99, 999, 'instock', 0.0, 'digital', '/uploads/products/productivity-suite-pro.jpg', 6, 'Productivity Suite Pro - Digital Tools', 'Boost productivity with our comprehensive digital suite featuring task management and collaboration tools.', 1, 1);

-- Insert sample users
INSERT INTO `users` (`username`, `email`, `password`, `first_name`, `last_name`, `phone`, `address`, `city`, `state`, `zip_code`, `country`, `is_active`, `email_verified`) VALUES
('john_doe', 'john@example.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'John', 'Doe', '+1-555-0101', '123 Main St', 'New York', 'NY', '10001', 'US', 1, 1),
('jane_smith', 'jane@example.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'Jane', 'Smith', '+1-555-0102', '456 Oak Ave', 'Los Angeles', 'CA', '90210', 'US', 1, 1),
('mike_wilson', 'mike@example.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'Mike', 'Wilson', '+1-555-0103', '789 Pine St', 'Chicago', 'IL', '60601', 'US', 1, 1);

-- Insert sample testimonials
INSERT INTO `testimonials` (`name`, `email`, `company`, `position`, `rating`, `testimonial`, `avatar`, `is_featured`, `is_published`) VALUES
('Mark Thompson', 'mark@audioengine.com', 'AudioEngine Studios', 'Senior Audio Engineer', 5, 'The ZenBuds Pro are the best wireless earbuds I have ever used. The sound quality is incredible for the price, and they are so comfortable that I can wear them for hours during long recording sessions.', '/uploads/avatars/mark-thompson.jpg', 1, 1),
('Sarah Kim', 'sarah@designco.com', 'Design Co.', 'Creative Director', 5, 'My order from SmartProZen arrived in just two days! The packaging was great and the SmartGlow light looks amazing on my desk. The quality exceeded my expectations. 10/10 would shop again.', '/uploads/avatars/sarah-kim.jpg', 1, 1),
('David Rodriguez', 'david@techstartup.com', 'TechStartup Inc.', 'CEO', 5, 'SmartProZen has become my go-to for all tech accessories. The ProCharge Wireless Stand has been a game-changer for my home office setup. Fast shipping and excellent customer service.', '/uploads/avatars/david-rodriguez.jpg', 1, 1),
('Lisa Chen', 'lisa@fitnesspro.com', 'Fitness Pro', 'Personal Trainer', 5, 'The ZenWatch Sport has revolutionized how I track my workouts and daily activities. The GPS accuracy is spot-on, and the 7-day battery life means I never worry about charging during long training sessions.', '/uploads/avatars/lisa-chen.jpg', 1, 1);
