-- The complete sitemap generation code from the previous response should be placed here.
-- It includes the XML header, loops through products, pages, and posts from the DB,
-- and prints them in the correct XML format.